version: '3'
services:
    php-apache-environment:
        container_name: php-apache
        image: php:8.1-apache
        volumes:
            - ./public/vhosts.conf:/etc/apache2/sites-enabled/vhosts.conf
            - .:/var/www/html
        ports:
            - 8000:80  

    mysql:
        image: mysql:8.0
        container_name: mysql
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        ports:
            - "3309:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: password

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            -   mysql
        restart: always
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mysql
            UPLOAD_LIMIT: 900M

volumes:
    db_data: {}

